### PR TITLE
Made a start with configure options

### PR DESCRIPTION
**Pull request by tjeb**
Removed existing makefile, added configure.ac and Makefile.in

The location of the silvia library can be set, and NFC/PCSC module building can be disabled.

pkgconfig call still needs to be moved in the makefile. And probably some other cleanups :)

### CODE REVIEW

**Comment by tjeb** [comment]
Just to be clear, this is just some effot to get started with something more than a hand-editable makefile;

If there's interest in this (not necessarily this particular patch but configure scripts in general), let me know what standards we're looking for as a minimum :)

BTW, one potential problem is the custom compilation check for libsilvia, I wasn't able to get AC_CHECK_LIB working with a pure c++ library without c-compatible exported functions.

**Comment by puiterwijk** [comment]
Sorry for the late response to this.
As said, I would love it if I could get a standards-compliant Makefile.in/Configure.ac.

Basically, the things I would like if possible would be to have the bin_PROGRAMS etc, so a more declarative definition of the parts to build.
This will probably require some changes to pam_irma to allow both PCSC and NFC in the same library where the specific implementation is selected by PAM configuration, I will add this later today.

AC_CHECK_LIB misses the silvia.pc (pkg-config definition) files in the silvia upstream, as that uses pkg-config.

**Comment by confiks** [comment]
Old PR is old.

**Comment by tjeb** [comment]
And now dead and buried :)

**Pull request closed without merging**
